### ISSUE TITLE
Image transforms

### ISSUE THREAD

**Issue by thijskaspers** [nystudio107/craft3-eagerbeaver#2]
Can this also be used for eager loading image transformations? If you eager load assets and loop over them, you'd still get a N+1 problem if each image has an image transformation applied.

The 'withTransforms' option below fixes this, but haven't figured out yet how to utilize that with eagerbeaver or the native Craft eagerLoadElements method.

````
{% set image = entry.imageField
    .withTransforms([
        'transformation'
    ])
    .one()
%}
````

**Comment by khalwat** [comment]
Currently, no, it does not do that.
